
services:
  mariadb:
    image: mariadb
    container_name: mariadb_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a!y2w4
      MYSQL_DATABASE: HsinyuOS
      MYSQL_USER: smitlea
      MYSQL_PASSWORD: 1234
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3310:3306"

  redis:
      image: redis
      command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
      ports:
        - "6379:6379"

volumes:
  mariadb_data:
